# Generated by Django 5.1.7 on 2025-03-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_update_on_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
